Idn lang
hiqdev/hiapi-heppy pull request #17
Opened 2020-02-04 09:03 UTC by bladeroot

2020-02-04 09:43 UTC, hiqsol requested changes

2020-02-04 09:43 UTC, hiqsol commented on src/helpers/LanguageHelper.php
> + * Fee class of EPP extension
поправь или выпили коммент

2020-02-04 09:43 UTC, hiqsol commented on src/extensions/AbstractExtension.php
> +        return explode('.', $name);
серьёзное изменение, точно всё работает после этого?

2020-02-04 09:43 UTC, hiqsol commented on src/helpers/LanguageHelper.php
> +         throw new \Exception('could not detect language');
а что дальше будет с этим эксепшеном? всё упадёт?

2020-02-04 09:46 UTC, SilverFire commented on src/extensions/AbstractExtension.php
> +        return explode('.', $name);
Вместе с этим изменением нужно править и PHPDoc

2020-02-04 09:51 UTC, bladeroot commented on src/extensions/AbstractExtension.php
> +        return explode('.', $name);
Изменение не серьезное. Вынесено в отдельную часть определение $name и разбивку на части имени.

2020-02-04 09:52 UTC, bladeroot commented on src/extensions/AbstractExtension.php
> +        return explode('.', $name);
PHPDoc поменял

2020-02-04 09:52 UTC, bladeroot commented on src/helpers/LanguageHelper.php
> + * Fee class of EPP extension
Готово

2020-02-04 10:03 UTC, hiqsol commented on src/helpers/LanguageHelper.php
> + * Fee class of EPP extension
что готово? коммент левый

2020-02-05 10:09 UTC, hiqsol approved these changes

2020-02-05 10:10 UTC, merged