AHN-69: fix creating contact - province length; add class property
hiqdev/hiapi-heppy pull request #56
Opened 2023-06-26 07:54 UTC by bladeroot

2023-06-26 11:09 UTC, hiqsol approved these changes

2023-06-26 11:10 UTC, hiqsol requested changes

2023-06-26 11:10 UTC, hiqsol commented on src/HeppyTool.php
> -            throw new InvalidCallException("module `$name` not found");
и что? тут остался пустой if?

2023-06-26 13:59 UTC, SilverFire commented on src/modules/ContactModule.php
> +                'cc'        => !empty($row['country']) ? strtoupper($row['country'] === 'gdpr' ? 'cy' : $row['country']) : null,
Looks awkward to me.
What does `country_code=gdpg` means? Why is it mapped to `cy`?

2023-06-27 11:54 UTC, bladeroot commented on src/modules/ContactModule.php
> +                'cc'        => !empty($row['country']) ? strtoupper($row['country'] === 'gdpr' ? 'cy' : $row['country']) : null,
Really it is alias for privacy. I think we could change to any

2023-07-03 15:04 UTC, hiqsol approved these changes

2023-07-03 15:04 UTC, merged